name: EGX Scraper

on:
  schedule:
     - cron: "0 7,12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug - list repo contents
        run: ls -la
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install beautifulsoup4 playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Run Scraper
        run: python scrape_egx.py

      - name: Commit JSON
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add egx.json
          git diff --cached --quiet || git commit -m "Update EGX data"
          git push
